# Generated by Django 2.1.7 on 2019-03-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ac_Admin', '0001_initial'),
        ('ac_Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('complaint_messgae', models.TextField()),
                ('complaint_image', models.ImageField(upload_to='complaints/')),
                ('Date_of_Register', models.DateField()),
                ('complaint_status', models.CharField(max_length=20)),
                ('Date_of_Close', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('msg', models.TextField()),
                ('image', models.ImageField(upload_to='feedback/')),
                ('feedbackid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Registration',
            fields=[
                ('citizen_id', models.AutoField(primary_key=True, serialize=False)),
                ('citizen_name', models.CharField(max_length=20)),
                ('citizen_contact', models.IntegerField()),
                ('citizen_Address', models.TextField()),
                ('citizen_city', models.CharField(max_length=20)),
                ('citizen_image', models.ImageField(upload_to='register/')),
                ('citizen_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_Login.Login_Details')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='citizenid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_Citizen.User_Registration'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='complaintid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_Citizen.complaint'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='citizen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_Citizen.User_Registration'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ac_Admin.Department'),
        ),
    ]
